local plugins = {
	"github/copilot.vim",
	"tpope/vim-fugitive",
	"tpope/vim-rhubarb",
	"tpope/vim-sleuth",
	"numToStr/Comment.nvim",
	"mbbill/undotree",
	"folke/which-key.nvim",
	"motiongorilla/p4nvim",
	"nvim-telescope/telescope.nvim",
	require("plugins.lsp"),
	require("plugins.cmp"),
	require("plugins.conform"),
	require("plugins.gitsigns"),
	require("plugins.onedark"),
	require("plugins.lualine"),
	require("plugins.indent"),
	require("plugins.fzf"),
	require("plugins.treesitter"),
	require("plugins.treesitter-textobjects"),
	require("plugins.neotree"),
	require("plugins.ufo"),
	require("plugins.bufferline"),
}

require("lazy").setup(plugins, {})
